"""Run-record persistence.

One run, one JSON file under `runs/`. That is the whole design: a record is
readable with `cat`, diffable in git, and openable in class with no network and
no provider. Records saved here are the classroom's primary asset — live runs
are the bonus.
"""

from __future__ import annotations

import json
from pathlib import Path

from .models import RecordSummary, RunRecord, summarise


class RunStore:
    def __init__(self, root: Path):
        self.root = Path(root)

    def ensure(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)

    def path_for(self, run_id: str) -> Path:
        # run_id is generated by us as a uuid4, but it round-trips through a
        # URL, so reject anything that is not already a plain filename stem
        # rather than quietly rewriting it into one.
        if not run_id or run_id != "".join(ch for ch in run_id if ch.isalnum() or ch in "-_"):
            raise ValueError(f"invalid run_id: {run_id!r}")
        return self.root / f"{run_id}.json"

    def save(self, record: RunRecord) -> Path:
        self.ensure()
        target = self.path_for(record.run_id)
        target.write_text(
            json.dumps(record.model_dump(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        return target

    def get(self, run_id: str) -> RunRecord | None:
        try:
            target = self.path_for(run_id)
        except ValueError:
            return None
        if not target.is_file():
            return None
        payload = json.loads(target.read_text(encoding="utf-8"))
        return RunRecord(**payload)

    def list_summaries(self, *, limit: int = 60) -> list[RecordSummary]:
        """Newest first, tolerant of a hand-edited or half-written file."""
        if not self.root.is_dir():
            return []
        summaries: list[RecordSummary] = []
        for path in self.root.glob("*.json"):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
                summaries.append(summarise(RunRecord(**payload)))
            except Exception:
                continue
        summaries.sort(key=lambda item: item.created_at, reverse=True)
        return summaries[:limit]

    def get_raw(self, run_id: str) -> dict | None:
        record = self.get(run_id)
        return record.model_dump() if record else None
